# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 671)
        MainWindow.setMaximumSize(QtCore.QSize(524305, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.knopf1 = QtWidgets.QPushButton(self.centralwidget)
        self.knopf1.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(47, 47, 53);\n"
"font: 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid #F62A53;\n"
"  padding: 10px 20px; /* Innenabstand (oben/unten links/rechts) */")
        self.knopf1.setObjectName("knopf1")
        self.gridLayout.addWidget(self.knopf1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.widgetFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetFrame.sizePolicy().hasHeightForWidth())
        self.widgetFrame.setSizePolicy(sizePolicy)
        self.widgetFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetFrame.setSizeIncrement(QtCore.QSize(0, 0))
        self.widgetFrame.setBaseSize(QtCore.QSize(0, 0))
        self.widgetFrame.setAcceptDrops(False)
        self.widgetFrame.setStyleSheet("")
        self.widgetFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.widgetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.widgetFrame.setLineWidth(1)
        self.widgetFrame.setObjectName("widgetFrame")
        self.gridLayout.addWidget(self.widgetFrame, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.kopfframe = QtWidgets.QFrame(self.centralwidget)
        self.kopfframe.setMaximumSize(QtCore.QSize(16777215, 80))
        self.kopfframe.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.kopfframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.kopfframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.kopfframe.setObjectName("kopfframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.kopfframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.kopfframe)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.kopfframe)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.uhrzeitFrame = QtWidgets.QFrame(self.kopfframe)
        self.uhrzeitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uhrzeitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.uhrzeitFrame.setObjectName("uhrzeitFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.uhrzeitFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.uhrzeitFrame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.uhrzeitFrame, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addWidget(self.kopfframe, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.knopf1.setText(_translate("MainWindow", "Drück mich zum Testen!"))
        self.label_2.setText(_translate("MainWindow", "Speed Test"))
        self.label.setText(_translate("MainWindow", "13:40:20"))
