# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'speedtestWidget_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_speedTest(object):
    def setupUi(self, speedTest):
        speedTest.setObjectName("speedTest")
        speedTest.resize(420, 300)
        speedTest.setMinimumSize(QtCore.QSize(420, 300))
        speedTest.setMaximumSize(QtCore.QSize(800, 700))
        speedTest.setStyleSheet("Form {\n"
"border-radius: 10px; /* Radius für abgerundete Ecken */\n"
" border: 2px solid #F62A53;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(speedTest)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(speedTest)
        self.frame_3.setStyleSheet("QFrame {\n"
"background-color: rgb(70 ,70 ,70);\n"
"}\n"
"QFrame#frame_3 {\n"
"    border-radius: 10px; /* Radius für abgerundete Ecken */\n"
"     border: 2px solid #000000;\n"
"    background-color: rgb(70 ,70 ,70);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.knopf = QtWidgets.QPushButton(self.frame_2)
        self.knopf.setMinimumSize(QtCore.QSize(100, 30))
        self.knopf.setStyleSheet("border-radius: 5px;\n"
"background-color: rgb(47, 47, 53);\n"
"font: 10pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"/* wird dymamisch im code geaender*/\n"
"border: 2px solid #F62A53;\n"
"/* --------------- */")
        self.knopf.setObjectName("knopf")
        self.horizontalLayout.addWidget(self.knopf, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setContentsMargins(-1, 0, 9, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.download = QtWidgets.QLabel(self.frame)
        self.download.setEnabled(True)
        self.download.setStyleSheet("font: 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.download.setText("")
        self.download.setObjectName("download")
        self.verticalLayout_2.addWidget(self.download)
        self.upload = QtWidgets.QLabel(self.frame)
        self.upload.setStyleSheet("font: 14pt \"Arial\";\n"
"color: rgb(255, 255, 255);    \n"
"")
        self.upload.setText("")
        self.upload.setObjectName("upload")
        self.verticalLayout_2.addWidget(self.upload)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.errorLabel = QtWidgets.QLabel(self.frame_3)
        self.errorLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout_3.addWidget(self.errorLabel, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(speedTest)
        QtCore.QMetaObject.connectSlotsByName(speedTest)

    def retranslateUi(self, speedTest):
        _translate = QtCore.QCoreApplication.translate
        speedTest.setWindowTitle(_translate("speedTest", "Form"))
        self.knopf.setText(_translate("speedTest", "Starten!"))
